name:                adventura
version:             0.1.0
github:              "RestitutorOrbis/adventura"
license:             GPL-3
author:              "Javed Nissar"
maintainer:          ""
copyright:           "none"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Text adventure game written in Haskell
category:            Text Adventure

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RestitutorOrbis/adventura#readme>

dependencies:
- base >= 4.7 && < 5
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: .

executables:
  adventura:
    main:                adventura.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventura
